// Code generated by ent, DO NOT EDIT.

package product

const (
	// Label holds the string label denoting the product type in the database.
	Label = "product"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldTitle holds the string denoting the title field in the database.
	FieldTitle = "title"
	// FieldImageUrl holds the string denoting the imageurl field in the database.
	FieldImageUrl = "image_url"
	// FieldSummary holds the string denoting the summary field in the database.
	FieldSummary = "summary"
	// FieldPrice holds the string denoting the price field in the database.
	FieldPrice = "price"
	// FieldQuantity holds the string denoting the quantity field in the database.
	FieldQuantity = "quantity"
	// EdgeSub holds the string denoting the sub edge name in mutations.
	EdgeSub = "sub"
	// EdgeCart holds the string denoting the cart edge name in mutations.
	EdgeCart = "cart"
	// Table holds the table name of the product in the database.
	Table = "products"
	// SubTable is the table that holds the sub relation/edge. The primary key declared below.
	SubTable = "sub_category_product"
	// SubInverseTable is the table name for the SubCategory entity.
	// It exists in this package in order to avoid circular dependency with the "subcategory" package.
	SubInverseTable = "sub_categories"
	// CartTable is the table that holds the cart relation/edge. The primary key declared below.
	CartTable = "product_cart"
	// CartInverseTable is the table name for the Cart entity.
	// It exists in this package in order to avoid circular dependency with the "cart" package.
	CartInverseTable = "carts"
)

// Columns holds all SQL columns for product fields.
var Columns = []string{
	FieldID,
	FieldTitle,
	FieldImageUrl,
	FieldSummary,
	FieldPrice,
	FieldQuantity,
}

var (
	// SubPrimaryKey and SubColumn2 are the table columns denoting the
	// primary key for the sub relation (M2M).
	SubPrimaryKey = []string{"sub_category_id", "product_id"}
	// CartPrimaryKey and CartColumn2 are the table columns denoting the
	// primary key for the cart relation (M2M).
	CartPrimaryKey = []string{"product_id", "cart_id"}
)

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}
