// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// CategoriesColumns holds the columns for the "categories" table.
	CategoriesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "title", Type: field.TypeString, Unique: true},
		{Name: "description", Type: field.TypeString},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// CategoriesTable holds the schema information for the "categories" table.
	CategoriesTable = &schema.Table{
		Name:       "categories",
		Columns:    CategoriesColumns,
		PrimaryKey: []*schema.Column{CategoriesColumns[0]},
	}
	// ProductsColumns holds the columns for the "products" table.
	ProductsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "title", Type: field.TypeString},
		{Name: "image_url", Type: field.TypeString},
		{Name: "summary", Type: field.TypeString},
		{Name: "price", Type: field.TypeFloat64},
		{Name: "quantity", Type: field.TypeInt},
	}
	// ProductsTable holds the schema information for the "products" table.
	ProductsTable = &schema.Table{
		Name:       "products",
		Columns:    ProductsColumns,
		PrimaryKey: []*schema.Column{ProductsColumns[0]},
	}
	// SubCategoriesColumns holds the columns for the "sub_categories" table.
	SubCategoriesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "title", Type: field.TypeString, Unique: true},
		{Name: "description", Type: field.TypeString},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "category_subs", Type: field.TypeInt, Nullable: true},
	}
	// SubCategoriesTable holds the schema information for the "sub_categories" table.
	SubCategoriesTable = &schema.Table{
		Name:       "sub_categories",
		Columns:    SubCategoriesColumns,
		PrimaryKey: []*schema.Column{SubCategoriesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "sub_categories_categories_subs",
				Columns:    []*schema.Column{SubCategoriesColumns[5]},
				RefColumns: []*schema.Column{CategoriesColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
	}
	// UsersColumns holds the columns for the "users" table.
	UsersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "username", Type: field.TypeString, Unique: true},
		{Name: "password", Type: field.TypeString},
		{Name: "role", Type: field.TypeEnum, Enums: []string{"admin", "user"}},
	}
	// UsersTable holds the schema information for the "users" table.
	UsersTable = &schema.Table{
		Name:       "users",
		Columns:    UsersColumns,
		PrimaryKey: []*schema.Column{UsersColumns[0]},
	}
	// SubCategoryProductColumns holds the columns for the "sub_category_product" table.
	SubCategoryProductColumns = []*schema.Column{
		{Name: "sub_category_id", Type: field.TypeInt},
		{Name: "product_id", Type: field.TypeInt},
	}
	// SubCategoryProductTable holds the schema information for the "sub_category_product" table.
	SubCategoryProductTable = &schema.Table{
		Name:       "sub_category_product",
		Columns:    SubCategoryProductColumns,
		PrimaryKey: []*schema.Column{SubCategoryProductColumns[0], SubCategoryProductColumns[1]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "sub_category_product_sub_category_id",
				Columns:    []*schema.Column{SubCategoryProductColumns[0]},
				RefColumns: []*schema.Column{SubCategoriesColumns[0]},
				OnDelete:   schema.Cascade,
			},
			{
				Symbol:     "sub_category_product_product_id",
				Columns:    []*schema.Column{SubCategoryProductColumns[1]},
				RefColumns: []*schema.Column{ProductsColumns[0]},
				OnDelete:   schema.Cascade,
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		CategoriesTable,
		ProductsTable,
		SubCategoriesTable,
		UsersTable,
		SubCategoryProductTable,
	}
)

func init() {
	SubCategoriesTable.ForeignKeys[0].RefTable = CategoriesTable
	SubCategoryProductTable.ForeignKeys[0].RefTable = SubCategoriesTable
	SubCategoryProductTable.ForeignKeys[1].RefTable = ProductsTable
}
