// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"shopular/ent/order"
	"shopular/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// OrderUpdate is the builder for updating Order entities.
type OrderUpdate struct {
	config
	hooks    []Hook
	mutation *OrderMutation
}

// Where appends a list predicates to the OrderUpdate builder.
func (ou *OrderUpdate) Where(ps ...predicate.Order) *OrderUpdate {
	ou.mutation.Where(ps...)
	return ou
}

// SetOrderDate sets the "order_date" field.
func (ou *OrderUpdate) SetOrderDate(t time.Time) *OrderUpdate {
	ou.mutation.SetOrderDate(t)
	return ou
}

// SetNillableOrderDate sets the "order_date" field if the given value is not nil.
func (ou *OrderUpdate) SetNillableOrderDate(t *time.Time) *OrderUpdate {
	if t != nil {
		ou.SetOrderDate(*t)
	}
	return ou
}

// ClearOrderDate clears the value of the "order_date" field.
func (ou *OrderUpdate) ClearOrderDate() *OrderUpdate {
	ou.mutation.ClearOrderDate()
	return ou
}

// SetShippingAddress sets the "shipping_address" field.
func (ou *OrderUpdate) SetShippingAddress(s string) *OrderUpdate {
	ou.mutation.SetShippingAddress(s)
	return ou
}

// SetPhone sets the "phone" field.
func (ou *OrderUpdate) SetPhone(s string) *OrderUpdate {
	ou.mutation.SetPhone(s)
	return ou
}

// SetPaymentMethod sets the "payment_method" field.
func (ou *OrderUpdate) SetPaymentMethod(om order.PaymentMethod) *OrderUpdate {
	ou.mutation.SetPaymentMethod(om)
	return ou
}

// SetTotalPrice sets the "total_price" field.
func (ou *OrderUpdate) SetTotalPrice(i int32) *OrderUpdate {
	ou.mutation.ResetTotalPrice()
	ou.mutation.SetTotalPrice(i)
	return ou
}

// AddTotalPrice adds i to the "total_price" field.
func (ou *OrderUpdate) AddTotalPrice(i int32) *OrderUpdate {
	ou.mutation.AddTotalPrice(i)
	return ou
}

// SetTrackingNumber sets the "tracking_number" field.
func (ou *OrderUpdate) SetTrackingNumber(s string) *OrderUpdate {
	ou.mutation.SetTrackingNumber(s)
	return ou
}

// SetOrderStatus sets the "order_status" field.
func (ou *OrderUpdate) SetOrderStatus(os order.OrderStatus) *OrderUpdate {
	ou.mutation.SetOrderStatus(os)
	return ou
}

// Mutation returns the OrderMutation object of the builder.
func (ou *OrderUpdate) Mutation() *OrderMutation {
	return ou.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (ou *OrderUpdate) Save(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(ou.hooks) == 0 {
		if err = ou.check(); err != nil {
			return 0, err
		}
		affected, err = ou.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*OrderMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = ou.check(); err != nil {
				return 0, err
			}
			ou.mutation = mutation
			affected, err = ou.sqlSave(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(ou.hooks) - 1; i >= 0; i-- {
			if ou.hooks[i] == nil {
				return 0, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = ou.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, ou.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// SaveX is like Save, but panics if an error occurs.
func (ou *OrderUpdate) SaveX(ctx context.Context) int {
	affected, err := ou.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (ou *OrderUpdate) Exec(ctx context.Context) error {
	_, err := ou.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ou *OrderUpdate) ExecX(ctx context.Context) {
	if err := ou.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (ou *OrderUpdate) check() error {
	if v, ok := ou.mutation.PaymentMethod(); ok {
		if err := order.PaymentMethodValidator(v); err != nil {
			return &ValidationError{Name: "payment_method", err: fmt.Errorf(`ent: validator failed for field "Order.payment_method": %w`, err)}
		}
	}
	if v, ok := ou.mutation.OrderStatus(); ok {
		if err := order.OrderStatusValidator(v); err != nil {
			return &ValidationError{Name: "order_status", err: fmt.Errorf(`ent: validator failed for field "Order.order_status": %w`, err)}
		}
	}
	return nil
}

func (ou *OrderUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   order.Table,
			Columns: order.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: order.FieldID,
			},
		},
	}
	if ps := ou.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := ou.mutation.OrderDate(); ok {
		_spec.SetField(order.FieldOrderDate, field.TypeTime, value)
	}
	if ou.mutation.OrderDateCleared() {
		_spec.ClearField(order.FieldOrderDate, field.TypeTime)
	}
	if value, ok := ou.mutation.ShippingAddress(); ok {
		_spec.SetField(order.FieldShippingAddress, field.TypeString, value)
	}
	if value, ok := ou.mutation.Phone(); ok {
		_spec.SetField(order.FieldPhone, field.TypeString, value)
	}
	if value, ok := ou.mutation.PaymentMethod(); ok {
		_spec.SetField(order.FieldPaymentMethod, field.TypeEnum, value)
	}
	if value, ok := ou.mutation.TotalPrice(); ok {
		_spec.SetField(order.FieldTotalPrice, field.TypeInt32, value)
	}
	if value, ok := ou.mutation.AddedTotalPrice(); ok {
		_spec.AddField(order.FieldTotalPrice, field.TypeInt32, value)
	}
	if value, ok := ou.mutation.TrackingNumber(); ok {
		_spec.SetField(order.FieldTrackingNumber, field.TypeString, value)
	}
	if value, ok := ou.mutation.OrderStatus(); ok {
		_spec.SetField(order.FieldOrderStatus, field.TypeEnum, value)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, ou.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{order.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	return n, nil
}

// OrderUpdateOne is the builder for updating a single Order entity.
type OrderUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *OrderMutation
}

// SetOrderDate sets the "order_date" field.
func (ouo *OrderUpdateOne) SetOrderDate(t time.Time) *OrderUpdateOne {
	ouo.mutation.SetOrderDate(t)
	return ouo
}

// SetNillableOrderDate sets the "order_date" field if the given value is not nil.
func (ouo *OrderUpdateOne) SetNillableOrderDate(t *time.Time) *OrderUpdateOne {
	if t != nil {
		ouo.SetOrderDate(*t)
	}
	return ouo
}

// ClearOrderDate clears the value of the "order_date" field.
func (ouo *OrderUpdateOne) ClearOrderDate() *OrderUpdateOne {
	ouo.mutation.ClearOrderDate()
	return ouo
}

// SetShippingAddress sets the "shipping_address" field.
func (ouo *OrderUpdateOne) SetShippingAddress(s string) *OrderUpdateOne {
	ouo.mutation.SetShippingAddress(s)
	return ouo
}

// SetPhone sets the "phone" field.
func (ouo *OrderUpdateOne) SetPhone(s string) *OrderUpdateOne {
	ouo.mutation.SetPhone(s)
	return ouo
}

// SetPaymentMethod sets the "payment_method" field.
func (ouo *OrderUpdateOne) SetPaymentMethod(om order.PaymentMethod) *OrderUpdateOne {
	ouo.mutation.SetPaymentMethod(om)
	return ouo
}

// SetTotalPrice sets the "total_price" field.
func (ouo *OrderUpdateOne) SetTotalPrice(i int32) *OrderUpdateOne {
	ouo.mutation.ResetTotalPrice()
	ouo.mutation.SetTotalPrice(i)
	return ouo
}

// AddTotalPrice adds i to the "total_price" field.
func (ouo *OrderUpdateOne) AddTotalPrice(i int32) *OrderUpdateOne {
	ouo.mutation.AddTotalPrice(i)
	return ouo
}

// SetTrackingNumber sets the "tracking_number" field.
func (ouo *OrderUpdateOne) SetTrackingNumber(s string) *OrderUpdateOne {
	ouo.mutation.SetTrackingNumber(s)
	return ouo
}

// SetOrderStatus sets the "order_status" field.
func (ouo *OrderUpdateOne) SetOrderStatus(os order.OrderStatus) *OrderUpdateOne {
	ouo.mutation.SetOrderStatus(os)
	return ouo
}

// Mutation returns the OrderMutation object of the builder.
func (ouo *OrderUpdateOne) Mutation() *OrderMutation {
	return ouo.mutation
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (ouo *OrderUpdateOne) Select(field string, fields ...string) *OrderUpdateOne {
	ouo.fields = append([]string{field}, fields...)
	return ouo
}

// Save executes the query and returns the updated Order entity.
func (ouo *OrderUpdateOne) Save(ctx context.Context) (*Order, error) {
	var (
		err  error
		node *Order
	)
	if len(ouo.hooks) == 0 {
		if err = ouo.check(); err != nil {
			return nil, err
		}
		node, err = ouo.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*OrderMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = ouo.check(); err != nil {
				return nil, err
			}
			ouo.mutation = mutation
			node, err = ouo.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(ouo.hooks) - 1; i >= 0; i-- {
			if ouo.hooks[i] == nil {
				return nil, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = ouo.hooks[i](mut)
		}
		v, err := mut.Mutate(ctx, ouo.mutation)
		if err != nil {
			return nil, err
		}
		nv, ok := v.(*Order)
		if !ok {
			return nil, fmt.Errorf("unexpected node type %T returned from OrderMutation", v)
		}
		node = nv
	}
	return node, err
}

// SaveX is like Save, but panics if an error occurs.
func (ouo *OrderUpdateOne) SaveX(ctx context.Context) *Order {
	node, err := ouo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (ouo *OrderUpdateOne) Exec(ctx context.Context) error {
	_, err := ouo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ouo *OrderUpdateOne) ExecX(ctx context.Context) {
	if err := ouo.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (ouo *OrderUpdateOne) check() error {
	if v, ok := ouo.mutation.PaymentMethod(); ok {
		if err := order.PaymentMethodValidator(v); err != nil {
			return &ValidationError{Name: "payment_method", err: fmt.Errorf(`ent: validator failed for field "Order.payment_method": %w`, err)}
		}
	}
	if v, ok := ouo.mutation.OrderStatus(); ok {
		if err := order.OrderStatusValidator(v); err != nil {
			return &ValidationError{Name: "order_status", err: fmt.Errorf(`ent: validator failed for field "Order.order_status": %w`, err)}
		}
	}
	return nil
}

func (ouo *OrderUpdateOne) sqlSave(ctx context.Context) (_node *Order, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   order.Table,
			Columns: order.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: order.FieldID,
			},
		},
	}
	id, ok := ouo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Order.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := ouo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, order.FieldID)
		for _, f := range fields {
			if !order.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != order.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := ouo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := ouo.mutation.OrderDate(); ok {
		_spec.SetField(order.FieldOrderDate, field.TypeTime, value)
	}
	if ouo.mutation.OrderDateCleared() {
		_spec.ClearField(order.FieldOrderDate, field.TypeTime)
	}
	if value, ok := ouo.mutation.ShippingAddress(); ok {
		_spec.SetField(order.FieldShippingAddress, field.TypeString, value)
	}
	if value, ok := ouo.mutation.Phone(); ok {
		_spec.SetField(order.FieldPhone, field.TypeString, value)
	}
	if value, ok := ouo.mutation.PaymentMethod(); ok {
		_spec.SetField(order.FieldPaymentMethod, field.TypeEnum, value)
	}
	if value, ok := ouo.mutation.TotalPrice(); ok {
		_spec.SetField(order.FieldTotalPrice, field.TypeInt32, value)
	}
	if value, ok := ouo.mutation.AddedTotalPrice(); ok {
		_spec.AddField(order.FieldTotalPrice, field.TypeInt32, value)
	}
	if value, ok := ouo.mutation.TrackingNumber(); ok {
		_spec.SetField(order.FieldTrackingNumber, field.TypeString, value)
	}
	if value, ok := ouo.mutation.OrderStatus(); ok {
		_spec.SetField(order.FieldOrderStatus, field.TypeEnum, value)
	}
	_node = &Order{config: ouo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, ouo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{order.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	return _node, nil
}
