// Code generated by ent, DO NOT EDIT.

package ent

import (
	"shopular/ent/category"
	"shopular/ent/schema"
	"shopular/ent/subcategory"
	"time"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	categoryFields := schema.Category{}.Fields()
	_ = categoryFields
	// categoryDescCreatedAt is the schema descriptor for created_at field.
	categoryDescCreatedAt := categoryFields[2].Descriptor()
	// category.DefaultCreatedAt holds the default value on creation for the created_at field.
	category.DefaultCreatedAt = categoryDescCreatedAt.Default.(func() time.Time)
	// categoryDescUpdatedAt is the schema descriptor for updated_at field.
	categoryDescUpdatedAt := categoryFields[3].Descriptor()
	// category.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	category.DefaultUpdatedAt = categoryDescUpdatedAt.Default.(func() time.Time)
	subcategoryFields := schema.SubCategory{}.Fields()
	_ = subcategoryFields
	// subcategoryDescCreatedAt is the schema descriptor for created_at field.
	subcategoryDescCreatedAt := subcategoryFields[2].Descriptor()
	// subcategory.DefaultCreatedAt holds the default value on creation for the created_at field.
	subcategory.DefaultCreatedAt = subcategoryDescCreatedAt.Default.(func() time.Time)
	// subcategoryDescUpdatedAt is the schema descriptor for updated_at field.
	subcategoryDescUpdatedAt := subcategoryFields[3].Descriptor()
	// subcategory.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	subcategory.DefaultUpdatedAt = subcategoryDescUpdatedAt.Default.(func() time.Time)
}
