// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Category is the predicate function for category builders.
type Category func(*sql.Selector)

// Product is the predicate function for product builders.
type Product func(*sql.Selector)

// SubCategory is the predicate function for subcategory builders.
type SubCategory func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
