// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Cart is the predicate function for cart builders.
type Cart func(*sql.Selector)

// Category is the predicate function for category builders.
type Category func(*sql.Selector)

// Customer is the predicate function for customer builders.
type Customer func(*sql.Selector)

// Order is the predicate function for order builders.
type Order func(*sql.Selector)

// Product is the predicate function for product builders.
type Product func(*sql.Selector)

// SubCategory is the predicate function for subcategory builders.
type SubCategory func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
